### ISSUE TITLE
[GeoDataAPI-GeoDataResults]Bug when parsing bestViewBox in .\Source\GeoDataAPI\Models\GeoDataResult.cs

### ISSUE THREAD

**Issue by alixiashu** [microsoft/BingMapsSDSToolkit#12]
When I tried to get the best view of polygons, I found that the source has a small bug when getting the best view box by parsing the EntityMetadata.BestMapViewBox. As the [GeoDataApi Doc](https://docs.microsoft.com/en-us/bingmaps/spatial-data-services/geodata-api) says, the BestMapViewBox is provided in the format of a **MULTIPOINT ((WestLongitude SouthLatitude), (EastLongitude NorthLatitude))**. But the when the code try to parse the string and get the north west coordinate and south east coordinate, it uses the wrong data with the index. Some fix should be like
![image](https://user-images.githubusercontent.com/28770220/185052007-a046b565-06c3-4605-b627-789677bd6f24.png)

**Comment by alixiashu** [comment]
@cschotte Could you help to clarify why you labeled it as "wontfix"? Do I understand it incorrectly?

**Comment by rbrundritt** [comment]
This has been fixed in the source code of this project. Note that the NuGet package has not been updated for some time and there is no timeline for updating it. You can download the source and reference it locally to access this and other updates that have been made since the last time the NuGet package has been updated.
