### ISSUE TITLE
GetBoundary fails when CurrentCulture.NumberFormat.NumberDecimalSeparator is not "."

### ISSUE THREAD

**Issue by markbeau** [microsoft/BingMapsSDSToolkit#5]
In GeoManager.cs, the latitude and longitude strings are not correctly rendered if CurrentCulture is for example IT (Italian) such that the decimal separator is "," rather than ".". 

One workaround is to set the separator to "." before calling GetBoundary(), and set it back after if necessary.
```c#
Thread.CurrentThread.CurrentCulture.NumberFormat.NumberDecimalSeparator = ".";
List<GeodataResult> results = await GeodataManager.GetBoundary(request, bingMapsKey);
````

**Comment by IoTGirl** [comment]
@justho Can you please review this issue?

**Comment by obert01** [comment]
Hello,

I have the same issue on a French Windows system. I am forced to change my Windows regional settings to English for using a specific client application, which is not confortable. 

Thank you in advance

**Comment by rbrundritt** [comment]
This has been fixed in the source code of this project. Note that the NuGet package has not been updated for some time and there is no timeline for updating it. You can download the source and reference it locally to access this and other updates that have been made since the last time the NuGet package has been updated.
